# created by hussainatphysics@gmail.com(hussainsha syed)
here we perfom all regression models like Support vector regression(SVR) random forest, decission tree, polynomial regression, multilinear regresion and Linear regression to conclude which is better for the taken dataset
here dataset we brest cancer worst features to predict fractal_dimension_worst

#  Importing libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing dataset

In [2]:
loadData = pd.read_csv("C:\\Users\\HussainSha\\ML_forGithub\\Regression_all_projecet\\brest_cancer_worst.csv")

In [3]:
loadData.head(5)

Unnamed: 0  radius_worst  texture_worst  perimeter_worst  area_worst  \
0           0         25.38          17.33           184.60      2019.0   
1           1         24.99          23.41           158.80      1956.0   
2           2         23.57          25.53           152.50      1709.0   
3           3         14.91          26.50            98.87       567.7   
4           4         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678

In [6]:
loadData1 = loadData.drop('Unnamed: 0', axis='columns')

In [7]:
loadData1.head(5)

radius_worst  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0         25.38          17.33           184.60      2019.0            0.1622   
1         24.99          23.41           158.80      1956.0            0.1238   
2         23.57          25.53           152.50      1709.0            0.1444   
3         14.91          26.50            98.87       567.7            0.2098   
4         22.54          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678

In [8]:
x = loadData1.drop('fractal_dimension_worst',axis='columns')

In [9]:
x.head(5)

radius_worst  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0         25.38          17.33           184.60      2019.0            0.1622   
1         24.99          23.41           158.80      1956.0            0.1238   
2         23.57          25.53           152.50      1709.0            0.1444   
3         14.91          26.50            98.87       567.7            0.2098   
4         22.54          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  
0             0.6656           0.7119                0.2654          0.4601  
1             0.1866           0.2416                0.1860          0.2750  
2             0.4245           0.4504                0.2430          0.3613  
3             0.8663           0.6869                0.2575          0.6638  
4             0.2050           0.4000                0.1625          0.2364

In [10]:
y = loadData1.drop(['radius_worst','texture_worst','perimeter_worst','area_worst','smoothness_worst','compactness_worst','concavity_worst','concave points_worst','symmetry_worst'], axis='columns')

In [11]:
y.head(5)

fractal_dimension_worst
0                  0.11890
1                  0.08902
2                  0.08758
3                  0.17300
4                  0.07678

# Feature scalling

In [12]:
from sklearn.preprocessing import StandardScaler

In [29]:
sc_X = StandardScaler()

In [30]:
sc_Y = StandardScaler()

In [26]:
x1 = x.to_numpy()

In [27]:
y1 = y.to_numpy()

In [31]:
X = sc_X.fit_transform(x)

In [32]:
Y = sc_Y.fit_transform(y)

# Support Vector Regression

In [35]:
from sklearn.svm import SVR

In [38]:
svr_reg = SVR(kernel='rbf')

In [39]:
svr_reg.fit(X, Y)

C:\Users\HussainSha\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

In [40]:
svr_pred = svr_reg.predict(X)

In [42]:
from sklearn.metrics import mean_squared_error

In [43]:
print("RMSE of SVR is", np.sqrt(mean_squared_error(Y, svr_pred)))

RMSE of SVR is 0.42337471772588436


In [44]:
svr_reg.score(X, Y)

0.8207538483905278

# Random forest

In [45]:
from sklearn.ensemble import RandomForestRegressor

In [68]:
ran_reg = RandomForestRegressor(n_estimators=200, random_state=0)

In [69]:
ran_reg.fit(X, Y)

<ipython-input-69-6c167b38d0d0>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  ran_reg.fit(X, Y)


RandomForestRegressor(n_estimators=200, random_state=0)

In [70]:
ran_pred = ran_reg.predict(X)

In [71]:
print("RMSE of Random forest is ", np.sqrt(mean_squared_error(Y, ran_pred)))

RMSE of Random forest is  0.18265453554263833


In [72]:
ran_reg.score(X, Y)

0.9666373206457031

#  Decission Tree

In [73]:
from sklearn.tree import DecisionTreeRegressor

In [74]:
dec_reg = DecisionTreeRegressor()

In [75]:
dec_reg.fit(X,Y)

DecisionTreeRegressor()

In [76]:
dec_pred = dec_reg.predict(X)

In [77]:
print("RMSE of Decission tree is ", np.sqrt(mean_squared_error(Y, dec_pred)))

RMSE of Decission tree is  0.0


In [78]:
dec_reg.score(X, Y)

1.0

# Polynomial regression

In [79]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [80]:
pol_reg = PolynomialFeatures(degree=10)

In [81]:
X_ = pol_reg.fit_transform(X)

In [82]:
lin_reg = LinearRegression()

In [83]:
lin_reg.fit(X_, Y)

LinearRegression()

In [84]:
pol_pred = lin_reg.predict(X_)

In [85]:
print('RMSE of polynomial regression', np.sqrt(mean_squared_error(Y, pol_pred)))

RMSE of polynomial regression 3.095806054512649e-09


In [86]:
lin_reg.score(X_, Y)

1.0

# Multilinear regression

In [87]:
lin_reg.fit(X, Y)

LinearRegression()

In [88]:
mulL_pred = lin_reg.predict(X)

In [89]:
lin_reg.coef_

array([[ 0.15472134, -0.02002274, -1.09705422,  0.52984703,  0.17659096,
         0.92233009,  0.11249607, -0.03164045, -0.00826256]])

In [90]:
lin_reg.intercept_

array([-5.03920771e-16])

In [91]:
print("RMSE of Multi linear regression", np.sqrt(mean_squared_error(Y, mulL_pred)))

RMSE of Multi linear regression 0.43240841938094143


In [92]:
lin_reg.score(X, Y)

0.8130229588484759

In [95]:
dict = {'RMSE of Multi SVR':np.sqrt(mean_squared_error(Y, svr_pred)),'RMSE of random forst regression':np.sqrt(mean_squared_error(Y, ran_pred)), 'RMSE of decission tree regression':np.sqrt(mean_squared_error(Y, dec_pred)), 'RMSE of polynomial regression':np.sqrt(mean_squared_error(Y, pol_pred)), 'RMSE of Multi linear regression':np.sqrt(mean_squared_error(Y, mulL_pred))}

In [96]:
dict

{'RMSE of Multi SVR': 0.42337471772588436,
 'RMSE of random forst regression': 0.18265453554263833,
 'RMSE of decission tree regression': 0.0,
 'RMSE of polynomial regression': 3.095806054512649e-09,
 'RMSE of Multi linear regression': 0.43240841938094143}

In [97]:
X

array([[ 1.88668963, -1.35929347,  2.30360062, ...,  2.10952635,
         2.29607613,  2.75062224],
       [ 1.80592744, -0.36920322,  1.53512599, ..., -0.14674897,
         1.0870843 , -0.24388967],
       [ 1.51187025, -0.02397438,  1.34747521, ...,  0.85497394,
         1.95500035,  1.152255  ],
       ...,
       [ 0.56136143,  1.37485378,  0.57900058, ...,  0.3267666 ,
         0.41406869, -1.10454895],
       [ 1.96123934,  2.23792588,  2.30360062, ...,  3.19760468,
         2.28998549,  1.91908301],
       [-1.41089258,  0.76418957, -1.43273495, ..., -1.30583065,
        -1.74506282, -0.04813821]])

In [98]:
Y

array([[ 1.93701461e+00],
       [ 2.81189987e-01],
       [ 2.01391209e-01],
       [ 4.93501034e+00],
       [-3.97099619e-01],
       [ 2.24180161e+00],
       [-1.47304787e-02],
       [ 1.72643451e+00],
       [ 1.28864955e+00],
       [ 6.84685604e+00],
       [ 3.18188080e-02],
       [ 1.15565159e+00],
       [ 1.01711204e+00],
       [-1.16793364e+00],
       [ 3.27807740e+00],
       [ 2.77933504e+00],
       [-9.89625213e-02],
       [ 1.67656027e+00],
       [-4.32011584e-01],
       [-6.29291894e-01],
       [-1.17249741e-01],
       [-3.44454593e-01],
       [ 8.59731121e-01],
       [-4.81331662e-01],
       [ 6.48042698e-01],
       [ 1.21660899e+00],
       [ 2.41359064e+00],
       [-5.39518270e-01],
       [ 8.20940049e-01],
       [-2.63547499e-01],
       [ 7.68849180e-01],
       [ 3.11737152e+00],
       [ 4.84435532e-02],
       [ 1.57127022e+00],
       [ 2.18084421e+00],
       [ 1.32121438e-01],
       [ 9.67237807e-01],
       [-1.23332430e+00],
       [-1.6

In [99]:
svr_pred

array([ 1.24295413e+00, -9.16026014e-01,  4.57256960e-01,  2.11590850e+00,
       -4.53898668e-01,  2.14180346e+00, -3.07445298e-01,  7.59851824e-01,
        2.18929928e+00,  3.42502827e+00, -8.42913685e-01,  1.25603729e+00,
        3.23603773e-03, -8.01681942e-01,  3.17276901e+00,  2.87964876e+00,
       -4.92065827e-01,  9.74770356e-01, -1.15542887e-01, -4.30210962e-01,
        1.73834802e-01, -2.51780784e-01,  9.60059390e-01, -5.51731456e-01,
        5.48084969e-01,  6.89369782e-01,  2.16870651e+00, -6.39740363e-01,
        1.94050294e+00, -2.64902434e-01,  5.49677084e-01,  2.07064950e+00,
        4.48599753e-01,  1.67169150e+00,  1.39693165e+00,  6.12765132e-01,
        1.06762360e+00, -1.24375300e+00, -1.28108303e+00,  7.17394302e-01,
       -6.36296095e-01,  7.71153091e-01,  1.20025748e+00,  7.26756024e-01,
        8.64087911e-01,  9.49426111e-01,  5.79276357e-02,  1.54944524e+00,
        4.52244151e-02, -7.18816855e-01, -9.37448049e-01, -7.43484693e-01,
       -8.95715630e-01, -

In [100]:
r1 = sc_Y.inverse_transform(Y)

In [101]:
r1

array([[0.1189 ],
       [0.08902],
       [0.08758],
       [0.173  ],
       [0.07678],
       [0.1244 ],
       [0.08368],
       [0.1151 ],
       [0.1072 ],
       [0.2075 ],
       [0.08452],
       [0.1048 ],
       [0.1023 ],
       [0.06287],
       [0.1431 ],
       [0.1341 ],
       [0.08216],
       [0.1142 ],
       [0.07615],
       [0.07259],
       [0.08183],
       [0.07773],
       [0.09946],
       [0.07526],
       [0.09564],
       [0.1059 ],
       [0.1275 ],
       [0.07421],
       [0.09876],
       [0.07919],
       [0.09782],
       [0.1402 ],
       [0.08482],
       [0.1123 ],
       [0.1233 ],
       [0.08633],
       [0.1014 ],
       [0.06169],
       [0.05504],
       [0.1071 ],
       [0.07146],
       [0.09606],
       [0.1038 ],
       [0.1027 ],
       [0.09618],
       [0.09185],
       [0.07409],
       [0.1179 ],
       [0.08301],
       [0.06917],
       [0.06563],
       [0.08025],
       [0.07408],
       [0.07987],
       [0.07873],
       [0.

In [102]:
r2 = sc_Y.inverse_transform(svr_pred)

In [103]:
r2

array([0.10637541, 0.06741577, 0.0921972 , 0.12212821, 0.07575504,
       0.12259549, 0.07839785, 0.09765764, 0.12345258, 0.14575179,
       0.06873511, 0.1066115 , 0.08400421, 0.06947915, 0.14119967,
       0.1359102 , 0.0750663 , 0.10153593, 0.0818608 , 0.07618249,
       0.08708273, 0.07940233, 0.10127046, 0.07398961, 0.09383622,
       0.09638576, 0.12308097, 0.07240145, 0.11896295, 0.07916555,
       0.09386495, 0.12131149, 0.09204097, 0.11411214, 0.10915399,
       0.0950034 , 0.1032115 , 0.06150181, 0.06082818, 0.09689148,
       0.07246361, 0.09786157, 0.10560493, 0.09706041, 0.09953862,
       0.10107858, 0.08499114, 0.11190616, 0.08476191, 0.07097449,
       0.0670292 , 0.07052935, 0.06778228, 0.07499893, 0.07487375,
       0.06924857, 0.09127592, 0.09646293, 0.06435218, 0.09206417,
       0.07796161, 0.09109026, 0.11929369, 0.08300449, 0.10665331,
       0.09459217, 0.0870673 , 0.07152789, 0.11569655, 0.06738861,
       0.06768963, 0.09020185, 0.12496001, 0.08956834, 0.07508

In [104]:
df2 = pd.DataFrame(r1)

In [105]:
df3 = pd.DataFrame(r2)

In [107]:
con = pd.concat([df2, df3], axis='columns')

In [109]:
con.head(5)

0         0
0  0.11890  0.106375
1  0.08902  0.067416
2  0.08758  0.092197
3  0.17300  0.122128
4  0.07678  0.075755